name: Generate Hamer Onion

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libsodium-dev

      - name: Clone mkp224o
        run: |
          git clone https://github.com/cathugger/mkp224o.git
          cd mkp224o
          make

      - name: Generate hamer.onion prefix
        run: |
          cd mkp224o
          ./mkp224o hamer

      - name: Upload generated keys
        uses: actions/upload-artifact@v4
        with:
          name: onion-service
          path: mkp224o/*